apiVersion: apps/v1
kind: Deployment
metadata:
  name: explorer.mynetwork.com
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hlf-explorer
  template:
    metadata:
      labels:
        app: hlf-explorer
    spec:
      
      networks:
        mynetwork.com:
          external:
            name: net_byfn
      volumes:
      - name: data
        emptyDir: {}
      - name: config
        configMap:
          name: hlf-scripts
      - name: crypto
        configMap:
          name: hlf-crypto  
      - name: connection
        configMap:
          name: hlf-connection  
      containers:
      - name: explorer
        image: hyperledger/explorer:latest
        hostname: explorer.mynetwork.com
      #  command: ["sh" , "-c" , "pg_isready -h localhost -p 5432 -q -U postgres"]
      #  command: ["sh" , "-c" , "cp /config/* /data/ && chmod -R 775 /data/ && /data/main.sh install"]
      #  command: ["sh" , "-c" , "main.sh install"]
      #  ./main.sh install
        command: ["sh" , "-c" , "cp /explorer/src/scripts/* /data/ && chmod -R 775 /data/ && /data/run.sh"]
      #  command: ["sh" , "-c" , "chmod -R 775 /opt/explorer/ && /opt/explorer/run.sh"]
      #  command: ["sh", "-c", "node blockchain-explorer/main.js && tail -f /dev/null"]
        
       

        env:
        
        
        volumeMounts:
        - mountPath: /data
          name: data
        - mountPath: /explorer/src/scripts
          name: config
        - mountPath: /opt/explorer/app/platform/fabric/config.json
          name: config
          subPath: config.json
        - mountPath: /tmp/crypto
          name: crypto
        - mountPath: /opt/explorer/app/platform/fabric/connection-profile
          name: connection
          
          
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP  
