apiVersion: v1
kind: Service
metadata:
  name: hlf-explorerdb
  labels:
    name: hlf-explorerdb
spec:
  type: ClusterIP
  selector:
    app: hlf-explorerdb
  ports:
  - protocol: TCP
    port: 5432
    name: http

