apiVersion: v1
kind: Service
metadata:
  name: hlf-explorer
  labels:
    name: hlf-explorer
spec:
  type: ClusterIP
  selector:
    app: hlf-explorer
  ports:
  - protocol: TCP
    port: 8080
    name: http
